server:
  port: 8080

  servlet:
    context-path: /api/v1

spring:
  application:
    name: uzum-product-service

  data:
    mongodb:
      uri: mongodb://localhost:27018/uzum-product-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
